backend: 
    name: github
    repo: happyrobotstudio/savio-ribiero

media_folder: static/assets
public_folder: assets


collections:
    - label: "Pages"
      name: "pages"
      files:
        - label: "Home Page"
          name: "home"
          file: "content/home.md"
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Subtite, name: subtitle, widget: text}
            - {label: About Savio text, name: aboutsavio, widget: text}
            - {label: Image, name: image, widget: image}
            - {label: Contact Button Message, name: contactmessage, widget: text}
            - {label: Contact Button Text, name: contacttext, widget: text}